#this scenario will be executed in case of creation of a Pull Request      !     
name: pull request logic

env:
  ENV_DESTRUCTIVE_DIFF_SF: ${{ vars.SF_COMMAND_META_STRING }}
  TARGET_BRANCH_NAME: "qa"
  SOURCE_BRANCH_NAME: "dev"
  DEV_SALESFORCE_AUTH_GITHUB_SECRET_VALUE: ${{ vars.PLATFORM_USERNAME_GITHUB_VARIABLE_VALUE}}
  SALESFORCE_ORG_ALIAS: ${{ vars.SALESFORCE_ORG_ALIAS }}
  ACCESS_KEY_SF: ${{ secrets.ACCESS_KEY_SF }}
  SALESFORCE_META_DIRECTORY: "force-app/main/default"
  APEX_TESTS_DIRECTORY: "force-app/main/default/classes/testFolder"



  
#  ENV_DESTRUCTIVE_DIFF_SFDX: ${{ vars.SFDX_COMMAND_META_STRING }}
#depends on the target branch one of the following scenarios:   
on:
  push:
    #PR target branch is: 
    branches:
      - 'dev**'
      - 'qa**'
      - 'staging**'
      - 'uat**'
      - 'prod**'


jobs:
  pre_deploy_logic:
    name: pre_deploy_logic
    environment: dev
    runs-on: ubuntu-latest
    steps:

      - name: --- System Step 0 ---. Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0


      - name: --- System Step 1 ---. Salesforce CLI install
        uses: sfdx-actions/setup-sfdx@v1


      - name: --- Global Step 0. Logger ---
        run: |
          chmod +x ./build/ci_cd_external_functions.sh
          source ./build/ci_cd_external_functions.sh && logger


      - name: --- Global Step 1. Salesforce login ---
        run: |
          chmod +x ./build/ci_cd_external_functions.sh
          source ./build/ci_cd_external_functions.sh && login_to_SF_org

          
      - name: --- Global Step 2. Get destractive meta list ---
        run: |
          chmod +x ./build/ci_cd_external_functions.sh
          source ./build/ci_cd_external_functions.sh && get_destructive_changes


#      - name: --- Global Step 4. Get positive meta list ---
#        run: |
#          chmod +x ./build/ci_cd_external_functions.sh
#          source ./build/ci_cd_external_functions.sh && get_positive_changes


#      - name: --- Global Step 5. Get apex tests list ---
#        run: |
#          chmod +x ./build/ci_cd_external_functions.sh
#          source ./build/ci_cd_external_functions.sh && get_apex_tests_list







#      - name: --- Global Step 3. Deploy destructive changes without saving ---
#        run: |
#          chmod +x ./build/ci_cd_external_functions.sh
#          source ./build/ci_cd_external_functions.sh && get_destructive_changes


          

#source ./build/ci_cd_external_functions.sh && login_to_SF_org_full_version1
         